### PR TITLE
strip the BOM if it's there

### PR DESCRIPTION
**Pull request by li-at-dw**
Implementing the fix suggested here
https://github.com/clojure/data.csv#byte-order-mark

### CODE REVIEW

**Comment by mrichards42** [comment]
I think you'll need to add that apache commons lib to `project.clj`

**Comment by li-at-dw** [comment]
Funny.... I was having trouble with that require, and I thought I had to include the dependency, and so I went looking for other code samples, and found one [here](https://github.com/democracyworks/upcoming-elections-demo/blob/master/src/upcoming_elections_demo/build.clj).  And that project didn't have the dependency, so I concluded that I didn't need it.  

(Happy to add it if you think leaving it out is bad practice--just mentioning this because I copied it from your code.  😉 )

**Comment by mrichards42** [comment]
That project actually does have the dependency -- it's `commons-io`, which I think I found by searching something like "maven apache commons"

**Comment by li-at-dw** [comment]
ah...thanks.  Second time today that I've been foiled by package names.

I'll add it.  Still confused how it worked without that dependency though.

**Comment by mrichards42** [comment]
That does seem suspicious . . . I'm betting it's b/c leiningen uses it: https://github.com/technomancy/leiningen/blob/1dc131128279ef50f21d4d643c4d5c2133c1370d/project.clj#L26

**Comment by li-at-dw** [comment]
Cool.  Thanks for helping me to draw the right conclusions from this exercise.

**Comment by tie-rack** [comment]
It happens that `commons-io` is a dependency of `clj-http`, which is why this works without explicitly depending on it, but it's good to be explicit.

**Pull request merged**
